name: CI

on:
  push:
    branches:
      - master
      - 'dev/**'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and run selenium tests
        run: |
          docker compose up --build --abort-on-container-exit --exit-code-from selenium-tests

      - name: Show logs on failure
        if: failure()
        run: |
          docker compose logs jupysql
          docker compose logs selenium-tests

  test:
    runs-on: ubuntu-latest

    env:
      PLOOMBER_VERSION_CHECK_DISABLED: true
      PYTHON_VERSION: '3.11'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade nox

      - name: Install test dependencies
        run: |
          nox --session test_unit --install-only

      - name: Test with pytest
        run: |
          nox --session test_unit --no-install --reuse-existing-virtualenvs

      - name: Upload failed images artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: failed-image-artifacts
          path: result_images/

  test-sqlalchemy-v1:
    runs-on: ubuntu-latest

    env:
      PLOOMBER_VERSION_CHECK_DISABLED: true
      PYTHON_VERSION: '3.11'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade nox

      - name: Install test dependencies
        run: |
          nox --session test_unit_sqlalchemy_one --install-only

      - name: Test with pytest
        run: |
          nox --session test_unit_sqlalchemy_one --no-install --reuse-existing-virtualenvs

      - name: Upload failed images artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: failed-image-artifacts-sqlalchemy
          path: result_images/

  release:
    needs: [selenium-tests, test, test-sqlalchemy-v1]
    if: startsWith(github.ref, 'refs/tags') && github.event_name != 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install pkgmt twine wheel setuptools --upgrade

      - name: Release
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: |
          echo "tag is $TAG"
          pkgmt release $TAG --production --yes
