name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    paths:
      - 'doc/**'
      - 'src/**'
      - '.github/workflows/deploy-docs.yaml'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge3
          miniforge-version: latest
          activate-environment: jupysql-docs
          use-mamba: true

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          mamba env update --file doc/environment.lock.yml --name jupysql-docs
          conda list

      - name: Build documentation
        shell: bash -l {0}
        run: |
          cd doc
          jupyter-book build . --warningiserror

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'doc/_build/html'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
